# Generated by Django 4.2.3 on 2023-09-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='character',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='price_type',
            field=models.CharField(choices=[("so'm", "so'm"), ('P', 'P'), ('$', '$')], default="so'm", max_length=10),
        ),
    ]
